import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/server";

// Handles legacy path-based tracking URLs:
// /api/track/click/{sendId}/{linkIndex}
// These were generated by an older version of the outreach template.
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ sendId: string; linkIndex: string }> },
) {
  const { sendId, linkIndex } = await params;
  const index = parseInt(linkIndex, 10);

  // Respond immediately — look up original URL and redirect
  try {
    const db = createAdminClient();

    const { data: link } = await db
      .from("outreach_tracked_links")
      .select("original_url")
      .eq("send_id", sendId)
      .eq("link_index", index)
      .single();

    if (link?.original_url) {
      // Fire-and-forget click recording
      db.rpc("track_click", { p_send_id: sendId, p_link_index: index }).then(undefined, () => {});
      return NextResponse.redirect(link.original_url);
    }
  } catch { /* fall through */ }

  return NextResponse.json({ error: "Link not found" }, { status: 404 });
}
