/**
 * Disposable / throwaway email domain list.
 * Sourced from well-known open lists.
 * Add more as needed — this is the core set of the most-used services.
 */
export const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com", "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
  "guerrillamail.biz", "guerrillamail.de", "guerrillamail.info",
  "10minutemail.com", "10minutemail.net", "10minutemail.org",
  "tempmail.com", "tempmail.net", "tempmail.org",
  "throwam.com", "throwam.net",
  "trashmail.com", "trashmail.net", "trashmail.org", "trashmail.at", "trashmail.io",
  "sharklasers.com", "guerrillamailblock.com", "grr.la", "guerrillamail.info",
  "spam4.me", "yopmail.com", "yopmail.fr", "cool.fr.nf", "jetable.fr.nf",
  "nospam.ze.tc", "nomail.xl.cx", "mega.zik.dj", "speed.1s.fr",
  "courriel.fr.nf", "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
  "dispostable.com", "mailnull.com", "maildrop.cc",
  "crap.handcrafted.jp", "fakeinbox.com", "mailnesia.com",
  "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
  "discard.email", "discardmail.com", "discardmail.de",
  "spamspot.com", "spamthisplease.com",
  "getonemail.com", "getonemail.net",
  "mailzilla.com", "mailzilla.org",
  "filzmail.com", "e4ward.com",
  "spaml.de", "kasmail.com", "spammotel.com",
  "greensloth.com", "spoofmail.de",
  "mytrashmail.com", "mt2009.com", "mt2014.com",
  "spambox.us", "spambox.info",
  "tempinbox.com", "tempinbox.co.uk",
  "mailbolt.com", "cheatmail.de", "teleworm.us",
  "dayrep.com", "einrot.com", "fleckens.hu",
  "gustr.com", "incognitomail.com",
  "jourrapide.com", "lookugly.com",
  "rhyta.com", "spamgob.com",
  "superrito.com", "superstachel.de",
  "teleworm.com",
  "armyspy.com", "cuvox.de",
  "zetmail.com", "mobi.web.id",
  "fg7.ru", "0815.ru", "0815.ry",
  "trbvm.com",
  "emlhub.com", "emlpro.com",
  "harakirimail.com",
  "inoutmail.de", "inoutmail.eu", "inoutmail.info", "inoutmail.net",
  "jetable.com", "jetable.fr", "jetable.net", "jetable.org",
  "keepmymail.com", "killmail.com", "killmail.net",
  "mail-temporaire.com", "mail-temporaire.fr",
  "mailforspam.com",
  "noclickemail.com", "no-spam.ws",
  "objectmail.com", "oneoffemail.com",
  "otherinbox.com",
  "pookmail.com",
  "powered.name",
  "rtrtr.com",
  "safe-mail.net",
  "skeefmail.com",
  "spam.la",
  "spaml.com",
  "stuffmail.de",
  "super-auswahl.de",
  "sweetxxx.de",
  "tafmail.com",
  "tempalias.com",
  "tempemailaddress.com",
  "thanksnospam.info",
  "thenulladdress.com",
  "throwam.com",
  "throwawayemailaddress.com",
  "tilien.com",
  "tmailinator.com",
  "tradermail.info",
  "veryrealemail.com",
  "wetrainbayarea.com",
  "whatparent.com",
  "yep.it",
  "z1p.biz",
  "zerotohero.ga",
]);
